name: Scrape and Deploy Website

on:
  schedule:
    - cron: "0 1 * * *"  # Runs daily at 01:00 UTC (8 PM EST)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install selenium pandas openpyxl webdriver-manager

      - name: Run scraper
        run: |
          python main.py

      - name: Commit and Push output
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add output/links_output.html
          git commit -m "Update links_output.html" || echo "No changes to commit"
          git push origin main
